version: '3'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongo:27017/
    depends_on:
      - mongo
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - ${PORT}
    depends_on:
      - mongo
    env_file:
      - .env
volumes:
  mongodata:
